//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 05:53:01 PM CET 
//


package rs.ac.uns.msb;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="list_item" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice minOccurs="0">
 *                   &lt;element ref="{http://www.uns.ac.rs/MSB}b"/>
 *                   &lt;element ref="{http://www.uns.ac.rs/MSB}i"/>
 *                   &lt;element ref="{http://www.uns.ac.rs/MSB}u"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
 *       &lt;attribute name="ordered_list" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}text_style"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listItem"
})
@XmlRootElement(name = "list")
public class List {

    @XmlElement(name = "list_item", required = true)
    protected java.util.List<List.ListItem> listItem;
    @XmlAttribute(name = "ID", namespace = "http://www.uns.ac.rs/MSB", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "ordered_list")
    protected Boolean orderedList;
    @XmlAttribute(name = "text_style", namespace = "http://www.uns.ac.rs/MSB")
    protected String textStyle;

    /**
     * Gets the value of the listItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link List.ListItem }
     * 
     * 
     */
    public java.util.List<List.ListItem> getListItem() {
        if (listItem == null) {
            listItem = new ArrayList<List.ListItem>();
        }
        return this.listItem;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the orderedList property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOrderedList() {
        if (orderedList == null) {
            return false;
        } else {
            return orderedList;
        }
    }

    /**
     * Sets the value of the orderedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOrderedList(Boolean value) {
        this.orderedList = value;
    }

    /**
     * Gets the value of the textStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextStyle() {
        return textStyle;
    }

    /**
     * Sets the value of the textStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextStyle(String value) {
        this.textStyle = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice minOccurs="0">
     *         &lt;element ref="{http://www.uns.ac.rs/MSB}b"/>
     *         &lt;element ref="{http://www.uns.ac.rs/MSB}i"/>
     *         &lt;element ref="{http://www.uns.ac.rs/MSB}u"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "b",
        "i",
        "u"
    })
    public static class ListItem {

        protected B b;
        protected I i;
        protected U u;

        /**
         * Gets the value of the b property.
         * 
         * @return
         *     possible object is
         *     {@link B }
         *     
         */
        public B getB() {
            return b;
        }

        /**
         * Sets the value of the b property.
         * 
         * @param value
         *     allowed object is
         *     {@link B }
         *     
         */
        public void setB(B value) {
            this.b = value;
        }

        /**
         * Gets the value of the i property.
         * 
         * @return
         *     possible object is
         *     {@link I }
         *     
         */
        public I getI() {
            return i;
        }

        /**
         * Sets the value of the i property.
         * 
         * @param value
         *     allowed object is
         *     {@link I }
         *     
         */
        public void setI(I value) {
            this.i = value;
        }

        /**
         * Gets the value of the u property.
         * 
         * @return
         *     possible object is
         *     {@link U }
         *     
         */
        public U getU() {
            return u;
        }

        /**
         * Sets the value of the u property.
         * 
         * @param value
         *     allowed object is
         *     {@link U }
         *     
         */
        public void setU(U value) {
            this.u = value;
        }

    }

}
