//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 05:53:01 PM CET 
//


package rs.ac.uns.msb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.uns.ac.rs/MSB}article_info"/>
 *         &lt;element name="review_form">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="technical_grade" type="{http://www.uns.ac.rs/MSB}Tgrade"/>
 *                   &lt;element name="language_grade" type="{http://www.uns.ac.rs/MSB}Tgrade"/>
 *                   &lt;element name="general_impression" type="{http://www.uns.ac.rs/MSB}Tform_item"/>
 *                   &lt;element name="good_sides" type="{http://www.uns.ac.rs/MSB}Tform_item"/>
 *                   &lt;element name="bad_sides" type="{http://www.uns.ac.rs/MSB}Tform_item"/>
 *                 &lt;/sequence>
 *                 &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="questionnaire">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="question" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="response">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="strongly disagree"/>
 *                                   &lt;enumeration value="disagree"/>
 *                                   &lt;enumeration value="neutral"/>
 *                                   &lt;enumeration value="agree"/>
 *                                   &lt;enumeration value="strongly agree"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="comments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="comment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="element_id" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="secret_comments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="secret_comment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="recommendation">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="accept"/>
 *               &lt;enumeration value="reject"/>
 *               &lt;enumeration value="major_revisions"/>
 *               &lt;enumeration value="minor_revisions"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleInfo",
    "reviewForm",
    "questionnaire",
    "comments",
    "secretComments",
    "recommendation"
})
@XmlRootElement(name = "review")
public class Review {

    @XmlElement(name = "article_info", required = true)
    protected ArticleInfo articleInfo;
    @XmlElement(name = "review_form", required = true)
    protected Review.ReviewForm reviewForm;
    @XmlElement(required = true)
    protected Review.Questionnaire questionnaire;
    @XmlElement(required = true)
    protected Review.Comments comments;
    @XmlElement(name = "secret_comments", required = true)
    protected Review.SecretComments secretComments;
    @XmlElement(required = true)
    protected String recommendation;
    
    @XmlAttribute(name = "paper_id", required = true)
    protected String paperId;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the articleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleInfo }
     *     
     */
    public ArticleInfo getArticleInfo() {
        return articleInfo;
    }

    /**
     * Sets the value of the articleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleInfo }
     *     
     */
    public void setArticleInfo(ArticleInfo value) {
        this.articleInfo = value;
    }

    /**
     * Gets the value of the reviewForm property.
     * 
     * @return
     *     possible object is
     *     {@link Review.ReviewForm }
     *     
     */
    public Review.ReviewForm getReviewForm() {
        return reviewForm;
    }

    /**
     * Sets the value of the reviewForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.ReviewForm }
     *     
     */
    public void setReviewForm(Review.ReviewForm value) {
        this.reviewForm = value;
    }

    /**
     * Gets the value of the questionnaire property.
     * 
     * @return
     *     possible object is
     *     {@link Review.Questionnaire }
     *     
     */
    public Review.Questionnaire getQuestionnaire() {
        return questionnaire;
    }

    /**
     * Sets the value of the questionnaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.Questionnaire }
     *     
     */
    public void setQuestionnaire(Review.Questionnaire value) {
        this.questionnaire = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link Review.Comments }
     *     
     */
    public Review.Comments getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.Comments }
     *     
     */
    public void setComments(Review.Comments value) {
        this.comments = value;
    }

    /**
     * Gets the value of the secretComments property.
     * 
     * @return
     *     possible object is
     *     {@link Review.SecretComments }
     *     
     */
    public Review.SecretComments getSecretComments() {
        return secretComments;
    }

    /**
     * Sets the value of the secretComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.SecretComments }
     *     
     */
    public void setSecretComments(Review.SecretComments value) {
        this.secretComments = value;
    }

    /**
     * Gets the value of the recommendation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendation() {
        return recommendation;
    }

    /**
     * Sets the value of the recommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendation(String value) {
        this.recommendation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="comment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="element_id" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "comment"
    })
    public static class Comments {

        protected List<Review.Comments.Comment> comment;

        /**
         * Gets the value of the comment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Review.Comments.Comment }
         * 
         * 
         */
        public List<Review.Comments.Comment> getComment() {
            if (comment == null) {
                comment = new ArrayList<Review.Comments.Comment>();
            }
            return this.comment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="element_id" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
         *       &lt;/sequence>
         *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Comment {

            @XmlElementRef(name = "element_id", namespace = "http://www.uns.ac.rs/MSB", type = JAXBElement.class)
            @XmlMixed
            protected List<Serializable> content;
            @XmlAttribute(name = "ID", namespace = "http://www.uns.ac.rs/MSB", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * {@link JAXBElement }{@code <}{@link Object }{@code >}
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="question" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="response">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="strongly disagree"/>
     *                         &lt;enumeration value="disagree"/>
     *                         &lt;enumeration value="neutral"/>
     *                         &lt;enumeration value="agree"/>
     *                         &lt;enumeration value="strongly agree"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Questionnaire {

        @XmlElement(required = true)
        protected List<Review.Questionnaire.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Review.Questionnaire.Item }
         * 
         * 
         */
        public List<Review.Questionnaire.Item> getItem() {
            if (item == null) {
                item = new ArrayList<Review.Questionnaire.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="question" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="response">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="strongly disagree"/>
         *               &lt;enumeration value="disagree"/>
         *               &lt;enumeration value="neutral"/>
         *               &lt;enumeration value="agree"/>
         *               &lt;enumeration value="strongly agree"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "question",
            "response"
        })
        public static class Item {

            @XmlElement(required = true)
            protected String question;
            @XmlElement(required = true)
            protected String response;

            /**
             * Gets the value of the question property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuestion() {
                return question;
            }

            /**
             * Sets the value of the question property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuestion(String value) {
                this.question = value;
            }

            /**
             * Gets the value of the response property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResponse() {
                return response;
            }

            /**
             * Sets the value of the response property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResponse(String value) {
                this.response = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="technical_grade" type="{http://www.uns.ac.rs/MSB}Tgrade"/>
     *         &lt;element name="language_grade" type="{http://www.uns.ac.rs/MSB}Tgrade"/>
     *         &lt;element name="general_impression" type="{http://www.uns.ac.rs/MSB}Tform_item"/>
     *         &lt;element name="good_sides" type="{http://www.uns.ac.rs/MSB}Tform_item"/>
     *         &lt;element name="bad_sides" type="{http://www.uns.ac.rs/MSB}Tform_item"/>
     *       &lt;/sequence>
     *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "technicalGrade",
        "languageGrade",
        "generalImpression",
        "goodSides",
        "badSides"
    })
    public static class ReviewForm {

        @XmlElement(name = "technical_grade", required = true)
        protected Tgrade technicalGrade;
        @XmlElement(name = "language_grade", required = true)
        protected Tgrade languageGrade;
        @XmlElement(name = "general_impression", required = true)
        protected TformItem generalImpression;
        @XmlElement(name = "good_sides", required = true)
        protected TformItem goodSides;
        @XmlElement(name = "bad_sides", required = true)
        protected TformItem badSides;
        @XmlAttribute(name = "ID", namespace = "http://www.uns.ac.rs/MSB")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the technicalGrade property.
         * 
         * @return
         *     possible object is
         *     {@link Tgrade }
         *     
         */
        public Tgrade getTechnicalGrade() {
            return technicalGrade;
        }

        /**
         * Sets the value of the technicalGrade property.
         * 
         * @param value
         *     allowed object is
         *     {@link Tgrade }
         *     
         */
        public void setTechnicalGrade(Tgrade value) {
            this.technicalGrade = value;
        }

        /**
         * Gets the value of the languageGrade property.
         * 
         * @return
         *     possible object is
         *     {@link Tgrade }
         *     
         */
        public Tgrade getLanguageGrade() {
            return languageGrade;
        }

        /**
         * Sets the value of the languageGrade property.
         * 
         * @param value
         *     allowed object is
         *     {@link Tgrade }
         *     
         */
        public void setLanguageGrade(Tgrade value) {
            this.languageGrade = value;
        }

        /**
         * Gets the value of the generalImpression property.
         * 
         * @return
         *     possible object is
         *     {@link TformItem }
         *     
         */
        public TformItem getGeneralImpression() {
            return generalImpression;
        }

        /**
         * Sets the value of the generalImpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link TformItem }
         *     
         */
        public void setGeneralImpression(TformItem value) {
            this.generalImpression = value;
        }

        /**
         * Gets the value of the goodSides property.
         * 
         * @return
         *     possible object is
         *     {@link TformItem }
         *     
         */
        public TformItem getGoodSides() {
            return goodSides;
        }

        /**
         * Sets the value of the goodSides property.
         * 
         * @param value
         *     allowed object is
         *     {@link TformItem }
         *     
         */
        public void setGoodSides(TformItem value) {
            this.goodSides = value;
        }

        /**
         * Gets the value of the badSides property.
         * 
         * @return
         *     possible object is
         *     {@link TformItem }
         *     
         */
        public TformItem getBadSides() {
            return badSides;
        }

        /**
         * Sets the value of the badSides property.
         * 
         * @param value
         *     allowed object is
         *     {@link TformItem }
         *     
         */
        public void setBadSides(TformItem value) {
            this.badSides = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="secret_comment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "secretComment"
    })
    public static class SecretComments {

        @XmlElement(name = "secret_comment")
        protected List<Review.SecretComments.SecretComment> secretComment;

        /**
         * Gets the value of the secretComment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the secretComment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSecretComment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Review.SecretComments.SecretComment }
         * 
         * 
         */
        public List<Review.SecretComments.SecretComment> getSecretComment() {
            if (secretComment == null) {
                secretComment = new ArrayList<Review.SecretComments.SecretComment>();
            }
            return this.secretComment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class SecretComment {

            @XmlElementRef(name = "password", namespace = "http://www.uns.ac.rs/MSB", type = JAXBElement.class)
            @XmlMixed
            protected List<Serializable> content;
            @XmlAttribute(name = "ID", namespace = "http://www.uns.ac.rs/MSB")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

        }

    }
    
    @Override
	public String toString() {
		StringBuilder builder = new StringBuilder("");
			builder.append("\nArticle info: ");
			builder.append("\n\tTitle: " + articleInfo.getTitle().getValue());
			builder.append("\n\tPublish date: " + articleInfo.getPublishDate());
			builder.append("\n\tPublisher: " + articleInfo.getPublisher());

			builder.append("\n***dodati ostalo");
	
			
			builder.append("\n");
		return builder.toString();
	}

	public String getPaperId() {
		return paperId;
	}

	public void setPaperId(String paperId) {
		this.paperId = paperId;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
