//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 05:53:01 PM CET 
//


package rs.ac.uns.msb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.uns.ac.rs/MSB}article_info"/>
 *         &lt;element name="authors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.uns.ac.rs/MSB}author" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="key_words">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="key_word" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.uns.ac.rs/MSB}abstract"/>
 *         &lt;element name="introduction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.uns.ac.rs/MSB}paragraph" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="chapters">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.uns.ac.rs/MSB}chapter" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="conclusion">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.uns.ac.rs/MSB}paragraph" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="references">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="reference" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="type">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice>
 *                                       &lt;element name="book" type="{http://www.uns.ac.rs/MSB}Treference_data"/>
 *                                       &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="paper" type="{http://www.uns.ac.rs/MSB}Treference_data"/>
 *                                     &lt;/choice>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="refNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
 *                           &lt;attribute ref="{http://www.uns.ac.rs/MSB}text_style"/>
 *                           &lt;attribute ref="{http://www.uns.ac.rs/MSB}text_size"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="paper_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleInfo",
    "authors",
    "keyWords",
    "_abstract",
    "introduction",
    "chapters",
    "conclusion",
    "references"
})
@XmlRootElement(name = "scientific_article")
public class ScientificArticle {

    @XmlElement(name = "article_info", required = true)
    protected ArticleInfo articleInfo;
    @XmlElement(required = true)
    protected ScientificArticle.Authors authors;
    @XmlElement(name = "key_words", required = true)
    protected ScientificArticle.KeyWords keyWords;
    @XmlElement(name = "abstract", required = true)
    protected Abstract _abstract;
    @XmlElement(required = true)
    protected ScientificArticle.Introduction introduction;
    @XmlElement(required = true)
    protected ScientificArticle.Chapters chapters;
    @XmlElement(required = true)
    protected ScientificArticle.Conclusion conclusion;
    @XmlElement(required = true)
    protected ScientificArticle.References references;
    @XmlAttribute(name = "ID"/*, namespace = "http://www.uns.ac.rs/MSB"*/, required = true)
    //@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    //@XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "version", required = true)
    protected double version;
    @XmlAttribute(name = "paper_type", required = true)
    protected String paperType;
    @XmlAttribute(name = "published", required = true)
    protected boolean published;

    /**
     * Gets the value of the articleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleInfo }
     *     
     */
    public ArticleInfo getArticleInfo() {
        return articleInfo;
    }

    /**
     * Sets the value of the articleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleInfo }
     *     
     */
    public void setArticleInfo(ArticleInfo value) {
        this.articleInfo = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link ScientificArticle.Authors }
     *     
     */
    public ScientificArticle.Authors getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScientificArticle.Authors }
     *     
     */
    public void setAuthors(ScientificArticle.Authors value) {
        this.authors = value;
    }

    /**
     * Gets the value of the keyWords property.
     * 
     * @return
     *     possible object is
     *     {@link ScientificArticle.KeyWords }
     *     
     */
    public ScientificArticle.KeyWords getKeyWords() {
        return keyWords;
    }

    /**
     * Sets the value of the keyWords property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScientificArticle.KeyWords }
     *     
     */
    public void setKeyWords(ScientificArticle.KeyWords value) {
        this.keyWords = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Abstract }
     *     
     */
    public Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abstract }
     *     
     */
    public void setAbstract(Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the introduction property.
     * 
     * @return
     *     possible object is
     *     {@link ScientificArticle.Introduction }
     *     
     */
    public ScientificArticle.Introduction getIntroduction() {
        return introduction;
    }

    /**
     * Sets the value of the introduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScientificArticle.Introduction }
     *     
     */
    public void setIntroduction(ScientificArticle.Introduction value) {
        this.introduction = value;
    }

    /**
     * Gets the value of the chapters property.
     * 
     * @return
     *     possible object is
     *     {@link ScientificArticle.Chapters }
     *     
     */
    public ScientificArticle.Chapters getChapters() {
        return chapters;
    }

    /**
     * Sets the value of the chapters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScientificArticle.Chapters }
     *     
     */
    public void setChapters(ScientificArticle.Chapters value) {
        this.chapters = value;
    }

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link ScientificArticle.Conclusion }
     *     
     */
    public ScientificArticle.Conclusion getConclusion() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScientificArticle.Conclusion }
     *     
     */
    public void setConclusion(ScientificArticle.Conclusion value) {
        this.conclusion = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ScientificArticle.References }
     *     
     */
    public ScientificArticle.References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScientificArticle.References }
     *     
     */
    public void setReferences(ScientificArticle.References value) {
        this.references = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public double getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(double value) {
        this.version = value;
    }

    /**
     * Gets the value of the paperType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperType() {
        return paperType;
    }

    /**
     * Sets the value of the paperType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperType(String value) {
        this.paperType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.uns.ac.rs/MSB}author" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "author"
    })
    public static class Authors {

        @XmlElement(required = true)
        protected List<Author> author;

        /**
         * Gets the value of the author property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the author property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuthor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Author }
         * 
         * 
         */
        public List<Author> getAuthor() {
            if (author == null) {
                author = new ArrayList<Author>();
            }
            return this.author;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.uns.ac.rs/MSB}chapter" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "chapter"
    })
    public static class Chapters {

        @XmlElement(required = true)
        protected List<Chapter> chapter;

        /**
         * Gets the value of the chapter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the chapter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChapter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Chapter }
         * 
         * 
         */
        public List<Chapter> getChapter() {
            if (chapter == null) {
                chapter = new ArrayList<Chapter>();
            }
            return this.chapter;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.uns.ac.rs/MSB}paragraph" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paragraph"
    })
    public static class Conclusion {

        @XmlElement(required = true)
        protected List<Paragraph> paragraph;
        @XmlAttribute(name = "ID", namespace = "http://www.uns.ac.rs/MSB", required = true)
        //@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        //@XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the paragraph property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the paragraph property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParagraph().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Paragraph }
         * 
         * 
         */
        public List<Paragraph> getParagraph() {
            if (paragraph == null) {
                paragraph = new ArrayList<Paragraph>();
            }
            return this.paragraph;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.uns.ac.rs/MSB}paragraph" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paragraph"
    })
    public static class Introduction {

        @XmlElement(required = true)
        protected List<Paragraph> paragraph;
        @XmlAttribute(name = "ID", namespace = "http://www.uns.ac.rs/MSB", required = true)
        //@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        //@XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the paragraph property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the paragraph property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParagraph().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Paragraph }
         * 
         * 
         */
        public List<Paragraph> getParagraph() {
            if (paragraph == null) {
                paragraph = new ArrayList<Paragraph>();
            }
            return this.paragraph;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="key_word" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "keyWord"
    })
    public static class KeyWords {

        @XmlElement(name = "key_word", required = true)
        protected List<String> keyWord;

        /**
         * Gets the value of the keyWord property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the keyWord property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKeyWord().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getKeyWord() {
            if (keyWord == null) {
                keyWord = new ArrayList<String>();
            }
            return this.keyWord;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="reference" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="type">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice>
     *                             &lt;element name="book" type="{http://www.uns.ac.rs/MSB}Treference_data"/>
     *                             &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="paper" type="{http://www.uns.ac.rs/MSB}Treference_data"/>
     *                           &lt;/choice>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="refNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
     *                 &lt;attribute ref="{http://www.uns.ac.rs/MSB}text_style"/>
     *                 &lt;attribute ref="{http://www.uns.ac.rs/MSB}text_size"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reference"
    })
    public static class References {

        @XmlElement(required = true)
        protected List<ScientificArticle.References.Reference> reference;

        /**
         * Gets the value of the reference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the reference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ScientificArticle.References.Reference }
         * 
         * 
         */
        public List<ScientificArticle.References.Reference> getReference() {
            if (reference == null) {
                reference = new ArrayList<ScientificArticle.References.Reference>();
            }
            return this.reference;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="type">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice>
         *                   &lt;element name="book" type="{http://www.uns.ac.rs/MSB}Treference_data"/>
         *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="paper" type="{http://www.uns.ac.rs/MSB}Treference_data"/>
         *                 &lt;/choice>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="refNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *       &lt;/sequence>
         *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}ID use="required""/>
         *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}text_style"/>
         *       &lt;attribute ref="{http://www.uns.ac.rs/MSB}text_size"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type",
            "refNumber"
        })
        public static class Reference {

            @XmlElement(required = true)
            protected ScientificArticle.References.Reference.Type type;
            @XmlElement(required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger refNumber;
            @XmlAttribute(name = "ID", namespace = "http://www.uns.ac.rs/MSB", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;
            @XmlAttribute(name = "text_style", namespace = "http://www.uns.ac.rs/MSB")
            protected String textStyle;
            @XmlAttribute(name = "text_size", namespace = "http://www.uns.ac.rs/MSB")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger textSize;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link ScientificArticle.References.Reference.Type }
             *     
             */
            public ScientificArticle.References.Reference.Type getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link ScientificArticle.References.Reference.Type }
             *     
             */
            public void setType(ScientificArticle.References.Reference.Type value) {
                this.type = value;
            }

            /**
             * Gets the value of the refNumber property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRefNumber() {
                return refNumber;
            }

            /**
             * Sets the value of the refNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRefNumber(BigInteger value) {
                this.refNumber = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the textStyle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTextStyle() {
                return textStyle;
            }

            /**
             * Sets the value of the textStyle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTextStyle(String value) {
                this.textStyle = value;
            }

            /**
             * Gets the value of the textSize property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTextSize() {
                return textSize;
            }

            /**
             * Sets the value of the textSize property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTextSize(BigInteger value) {
                this.textSize = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice>
             *         &lt;element name="book" type="{http://www.uns.ac.rs/MSB}Treference_data"/>
             *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="paper" type="{http://www.uns.ac.rs/MSB}Treference_data"/>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "book",
                "link",
                "paper"
            })
            public static class Type {

                protected TreferenceData book;
                protected Object link;
                protected TreferenceData paper;

                /**
                 * Gets the value of the book property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TreferenceData }
                 *     
                 */
                public TreferenceData getBook() {
                    return book;
                }

                /**
                 * Sets the value of the book property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TreferenceData }
                 *     
                 */
                public void setBook(TreferenceData value) {
                    this.book = value;
                }

                /**
                 * Gets the value of the link property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getLink() {
                    return link;
                }

                /**
                 * Sets the value of the link property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setLink(Object value) {
                    this.link = value;
                }

                /**
                 * Gets the value of the paper property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TreferenceData }
                 *     
                 */
                public TreferenceData getPaper() {
                    return paper;
                }

                /**
                 * Sets the value of the paper property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TreferenceData }
                 *     
                 */
                public void setPaper(TreferenceData value) {
                    this.paper = value;
                }

            }

        }

    }


	public boolean getPublished() {
		return published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

}
